import type { Metadata } from "next";
import {Caprasimo } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header/Header";

const caprasimo = Caprasimo({
  variable: "--font-caprasimo",
  subsets: ["latin"],
  weight: ['400'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`caprasimo.variable`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
